### ISSUE TITLE
It doesn't seem to be playing sound on Chrome?

### ISSUE THREAD

**Issue by lukaadam** [mathhulk/pnrtscr.com#2]
I don't know if it is just for me, but the sound doesn't play in Google Chrome.

**Comment by lukaadam** [comment]
Same issue on my mobile phone

**Comment by mathhulk** [comment]
Chrome and other browsers disable autoplay video when not muted to protect users and counteract disruptive and invasive media. This project used a quick hack to separate the audio and video into separate files in order to autoplay muted video and autoplay audio, but Chrome and other browsers seem to have become more strict and disabled the ability to autoplay audio when muted video autoplays as well. I’ll have to find another way around this eventually.

**Comment by mathhulk** [comment]
https://pnrtscr.com/wefh21
Abusing users' trust in cookie policy banners to bait a `click` event.
